services:
  db:
    image: postgres:16-alpine
    container_name: fmu_db
    environment:
      POSTGRES_DB: fmu_platform
      POSTGRES_USER: fmu_platform
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - fmu_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fmu_backend
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
    ports:
      - "127.0.0.1:8010:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: fmu_frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  fmu_db_data:
